### ISSUE TITLE
Binding multiple attributes with f-bind is not possible 

### ISSUE THREAD

**Issue by madx** [fluorjs/fluor#15]
Because of how HTML/the DOM works, you cannot have multiple `f-bind` directives.
There should be a ways to bind multiple attributes with a single directive.
I think the following syntax should be fine

```html
<div f-bind="attr1:value1,attr2:value2,     attr3:value3"></div>
```

I think spaces should be handled for readability of the code.

**Comment by y-nk** [comment]
You can go for VueJS style parameters: `f-bind:key="value"` and it will still be a valid html attribute.

**Comment by madx** [comment]
Yeah but it wouldn't work with React's JSX then, and I'm not ready to close that door :)

**Comment by madx** [comment]
Plus it's another new weird syntax lol

**Comment by madx** [comment]
The only proposal that would work when used with JSX is `f-bind-attr="value"`. That could actually make sense, avoid cryptic syntax and would be quite easy to handle in the language.

**Comment by madx** [comment]
This wouldn't work with some specific attributes like `xml:lang` but it's enough of an edge case for me not to want to bother with it, so dashes it is!
